(include_subdirs unqualified)

(library
 (name dream_lib)
 (modules ast error types env const_eval lexer parser exhaustiveness monomorphize
          dir dir_verify dir_printer dir_lower_llvm dir_lower
          dir_compiler
          symbol_analyzer module_loader
          tc_utils tc_generics tc_expr tc_stmt tc_defaults typeck))

(menhir
 (modules parser))

(ocamllex
 (modules lexer))
